### ISSUE TITLE
[Feature Request] Disable Push to Talk while typing in chat

### ISSUE THREAD

**Issue by HHammond** [keyfer/public-mes#18]
Right now within meetings I often want to write a comment or post a link to chat, but end up spamming the meeting with the sounds of my mechanical keyboard after I press Shift to capitalize the first character of my message. 

If MES could ignore the shift key while the chat drawer is open it would be really helpful, alternatively an easy toggle for push to talk that's accessible in fullscreen would be good.

**Comment by keyfer** [comment]
Hey @HHammond -

This should be fixed come release 3.2.
